name: NGINX CI

on:
  push:
    branches:
      - main

jobs:
  test-kubernetes-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install kubectl
        uses: azure/k8s-set-context@v1
        with:
          install-kubectl: true

      - name: Validate Kubernetes manifests
        run: |
          kubectl apply -f https://github.com/HemavathiSundar/aksCI/blob/main/yaml/nginx.yml --dry-run=client
          kubectl apply -f https://github.com/HemavathiSundar/aksCI/blob/main/yaml/nginx-service.yml --dry-run=client
