name: NGINX CI

on:
  push:
    branches:
      - main

jobs:
  test-kubernetes-manifests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo add-apt-repository "deb https://apt.kubernetes.io/ kubernetes-xenial main"
          sudo apt-get update
          sudo apt-get install -y kubectl
      
      - name: Validate Kubernetes manifests
        run: |
          kubectl apply -f https://github.com/HemavathiSundar/aksCI/blob/main/yaml/nginx.yml --dry-run=client
          kubectl apply -f https://github.com/HemavathiSundar/aksCI/blob/main/yaml/nginx-service.yml --dry-run=client
